###
GET http://localhost:4004/odata/v4/catalog/Books



###
POST http://localhost:4004/odata/v4/catalog/Books
Content-Type: application/json

{
  "ID": 220,
  "title": "Deep",
  "stock": 510,
  "author":"Kavya"
}


###
PATCH http://localhost:4004/odata/v4/catalog/Books(220)
Content-Type: application/json

{
    "stock": 100
}


###
POST  http://localhost:4004/odata/v4/catalog/updateData
Content-Type: application/json

{
  "id":1,
  "stock": 210
}




